export const QUERY_NAME = {
  VALIDATE_NICKNAME: "VALIDATE_NICKNAME",
  GET_POSITION_LIST: "GET_POSITION_LIST",
  GET_WORKING_YEAR_LIST: "GET_WORKING_YEAR_LIST",
  GET_CAFE_PINS: "GET_CAFE_PINS",
  GET_CAFE: "GET_CAFE",
  GET_DINER_PINS: "GET_DINER_PINS",
  GET_DINER: "GET_DINER",
  GET_WORKER_PINS: "GET_WORKER_PINS",
  GET_WORKER: "GET_WORKER",
  GET_USER_ADDRESS: "GET_USER_LOCATION",
} as const;
