export const QUERY_NAME = {
  VALIDATE_NICKNAME: "VALIDATE_NICKNAME",
  GET_POSITION_LIST: "GET_POSITION_LIST",
  GET_WORKING_YEAR_LIST: "GET_WORKING_YEAR_LIST",
  GET_TEST: "GET_TEST",
  GET_INFINITE_TEST: "GET_TEST",
};
